/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATA.GlobalVariables;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlo
 */
public class OptionClient extends javax.swing.JFrame {

    /**
     * Creates new form OptionClient
     */
    public OptionClient() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabelNombre.setText(GlobalVariables.loggedClient.getNames() + " " + GlobalVariables.loggedClient.getLastnames());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jButtonMisEventos = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonEditPerfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fecha_hora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jPanel2.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 470, 30));

        jButtonMisEventos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMisEventos.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonMisEventos.setText("MIS ENVENTOS");
        jButtonMisEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisEventosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMisEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 490, 60));

        jButtonRegresar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jButtonRegresar.setText("REGRESAR");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 750, 140, 30));

        jButtonEditPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditPerfil.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonEditPerfil.setText("EDITAR PERFIL");
        jButtonEditPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 490, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        fecha_hora.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        fecha_hora.setForeground(new java.awt.Color(255, 255, 255));
        fecha_hora.setText("23/07/2019 | 17:12");
        jPanel2.add(fecha_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 460, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOJA EVENTOS (3).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 790));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMisEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisEventosActionPerformed
        // TODO add your handling code here:

//        listEvents objEvents = new listEvents();
//        objEvents.setVisible(true);
//        this.setVisible(false);
        try {
            // TODO add your handling code here:

            CreateEvent objCreateEvent = new CreateEvent();
            objCreateEvent.setVisible(true);
            this.setVisible(false);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(OptionClient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonMisEventosActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        try {
            Login objLogin = new Login();
            objLogin.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CreateEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonEditPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPerfilActionPerformed
        // TODO add your handling code here:
        CreateAccount objCreateAccount = new CreateAccount();
        objCreateAccount.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha_hora;
    private javax.swing.JButton jButtonEditPerfil;
    private javax.swing.JButton jButtonMisEventos;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
