/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BLEvent;
import CLASES.Events;
import GUI.Login;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JIMMY
 */
public class validateEvents extends javax.swing.JFrame {

    ArrayList<Events> arrayEvents = new ArrayList();
    BLEvent objBLEvents = new BLEvent();
    Events objEvents = new Events();
    
    int rowSel = -1;
    /**
     * Creates new form crearEvento
     */
    public validateEvents() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SpnCosto = new javax.swing.JSpinner();
        cbmCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrinStr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSecStr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtReferency = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtnNeighborhod = new javax.swing.JTextField();
        jComboBoxHour = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxMinute = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonListar = new javax.swing.JButton();
        jButtonAprobar = new javax.swing.JButton();
        jButtonRechazar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del evento:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtNombre.setEnabled(false);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 280, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora de inicio");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        SpnCosto.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        SpnCosto.setEnabled(false);
        jPanel2.add(SpnCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));

        cbmCategory.setEnabled(false);
        jPanel2.add(cbmCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 160, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripcion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtDescription.setEnabled(false);
        jPanel2.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 320, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Calle Principal");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtPrinStr.setEnabled(false);
        jPanel2.add(txtPrinStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 320, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Calle Secundaria");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtSecStr.setEnabled(false);
        jPanel2.add(txtSecStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 320, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Referencia");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtReferency.setEnabled(false);
        jPanel2.add(txtReferency, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 320, -1));

        jDateChooser.setEnabled(false);
        jPanel2.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 150, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Barrio");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        txtnNeighborhod.setEnabled(false);
        jPanel2.add(txtnNeighborhod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 320, -1));

        jComboBoxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBoxHour.setEnabled(false);
        jPanel2.add(jComboBoxHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 70, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Costo de entrada");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 40, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Minutos");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 60, -1));

        jComboBoxMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jComboBoxMinute.setEnabled(false);
        jPanel2.add(jComboBoxMinute, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 70, -1));

        jLabel14.setText(":");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 10, -1));

        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title7", "Title 8"
            }
        ));
        tblEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEventos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 870, 200));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Validar Eventos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jButtonListar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonListar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 110, -1));

        jButtonAprobar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAprobar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonAprobar.setText("Aprobar");
        jButtonAprobar.setEnabled(false);
        jButtonAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAprobarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 110, -1));

        jButtonRechazar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRechazar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonRechazar.setText("Rechazar");
        jButtonRechazar.setEnabled(false);
        jButtonRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechazarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 110, -1));

        jButtonRegresar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 750, 100, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOJA EVENTOS (6).png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 790));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventosMouseClicked

        this.cbmCategory.removeAllItems();
        rowSel = tblEventos.getSelectedRow();
        this.txtNombre.setText(tblEventos.getValueAt(rowSel, 0).toString());
        this.SpnCosto.setValue(Double.parseDouble(tblEventos.getValueAt(rowSel, 1).toString()));
        this.jDateChooser.setDate(Date.valueOf(tblEventos.getValueAt(rowSel, 2).toString()));
        this.jComboBoxHour.setSelectedItem(arrayEvents.get(rowSel).getHour());
        this.jComboBoxMinute.setSelectedItem(arrayEvents.get(rowSel).getMinutes());
        this.cbmCategory.addItem(tblEventos.getValueAt(rowSel, 4).toString());
        this.txtDescription.setText(tblEventos.getValueAt(rowSel, 3).toString());
        this.txtPrinStr.setText(tblEventos.getValueAt(rowSel, 5).toString());
        this.txtSecStr.setText(tblEventos.getValueAt(rowSel, 6).toString());
        this.txtReferency.setText(tblEventos.getValueAt(rowSel, 7).toString());
        this.txtnNeighborhod.setText(tblEventos.getValueAt(rowSel, 8).toString());
        this.jButtonAprobar.setEnabled(true);
        this.jButtonRechazar.setEnabled(true);
    }//GEN-LAST:event_tblEventosMouseClicked

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // Listar eventos
        this.uploadTable();
        
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        try {
            // TODO add your handling code here:
            Login objLogin = new Login();
            objLogin.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(validateEvents.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAprobarActionPerformed
        // TODO add your handling code here:
        if (rowSel != -1) {
            objEvents = arrayEvents.get(rowSel);
            try {
                objBLEvents.updateState(objEvents, 2);
                JOptionPane.showMessageDialog(null, "El evento ha sido APROBADO");
                cleanText();
                this.jButtonListarActionPerformed(evt);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(validateEvents.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado nada");
        }
    }//GEN-LAST:event_jButtonAprobarActionPerformed

    private void jButtonRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechazarActionPerformed
        // TODO add your handling code here:
        if (rowSel != -1) {
            objEvents = arrayEvents.get(rowSel);
            try {
                objBLEvents.updateState(objEvents, 3);
                JOptionPane.showMessageDialog(null, "El evento ha sido RECHAZADO");
                cleanText();
                this.jButtonListarActionPerformed(evt);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(validateEvents.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado nada");
        }
    }//GEN-LAST:event_jButtonRechazarActionPerformed
   

    public void uploadTable() {
        // Listar todos los datos
        this.uploadArrayEvents();
        tblEventos.removeAll();
        Object columnas[] = {"Nombre", "Costo", "Fecha", "Descripcion", "Categoria", "Calle Principal", "Calle Secundaria", "Referencia", "Barrio"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        tblEventos.setModel(modelo);
        for (Events event : arrayEvents) {
            String newValor[] = {event.getName(), event.getCost() + "", event.getDate() + "", event.getDescription(), event.getCategory().getCategoryName(),
                event.getPlace().getPrincipalStreet(), event.getPlace().getSecondaryStreet(), event.getPlace().getReference(), event.getPlace().getNeighborhood().getName()};

            modelo.addRow(newValor);

        }
    }
    
    // Metodo para actualizar la varible local de arrayEvents
    public void uploadArrayEvents() {
        this.arrayEvents = objBLEvents.listEventsWhereState(1);
    }
    
    public void cleanText() {
        this.cbmCategory.removeAllItems();
        this.txtDescription.setText("");
        this.txtNombre.setText("");
        this.SpnCosto.setValue(0);
        this.jDateChooser.setDate(new java.util.Date());
        this.jComboBoxHour.setSelectedIndex(0);
        this.jComboBoxMinute.setSelectedIndex(0);
        this.txtDescription.setText("");
        this.txtPrinStr.setText("");
        this.txtSecStr.setText("");
        this.txtReferency.setText("");
        this.txtnNeighborhod.setText("");
        this.jButtonAprobar.setEnabled(false);
        this.jButtonRechazar.setEnabled(false);

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(validateEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(validateEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(validateEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(validateEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new validateEvents().setVisible(true);
            }
        });
    }
    
    
   
   
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnCosto;
    private javax.swing.JComboBox<String> cbmCategory;
    private javax.swing.JButton jButtonAprobar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonRechazar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxHour;
    private javax.swing.JComboBox<String> jComboBoxMinute;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEventos;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrinStr;
    private javax.swing.JTextField txtReferency;
    private javax.swing.JTextField txtSecStr;
    private javax.swing.JTextField txtnNeighborhod;
    // End of variables declaration//GEN-END:variables
}
