/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BLClient;
import java.util.*;
import javax.swing.JOptionPane;
import CLASES.Client;
import DATA.GlobalVariables;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hxpuc
 */
public class CreateAccount extends javax.swing.JFrame {

    BLClient ObjBLCli = new BLClient();
    Client objClient = new Client();

//    Login_V31 login_V31 = new Login_V31();
    public CreateAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
        validateLogin();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtIidentification = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtPasswordConf = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanelBotons = new javax.swing.JPanel();
        btnCrearCuenta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Cédula: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtIidentification.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtIidentification.setForeground(new java.awt.Color(102, 102, 102));
        txtIidentification.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtIidentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 400, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        txtName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 400, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Apellido: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 400, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Correo Electrónico: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        txtEmail1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtEmail1.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 350, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Número de teléfono: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(102, 102, 102));
        txtNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 350, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Contraseña: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 350, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Confirmación de contraseña: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        txtPasswordConf.setForeground(new java.awt.Color(102, 102, 102));
        txtPasswordConf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtPasswordConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 260, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBotons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotons.setForeground(new java.awt.Color(240, 240, 240));
        jPanelBotons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearCuenta.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnCrearCuenta.setText("Crear");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanelBotons.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanelBotons.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 30));

        jButtonMod.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jButtonMod.setText("Modificar");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });
        jPanelBotons.add(jButtonMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        jButtonSalir.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelBotons.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        jPanel1.add(jPanelBotons, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 130, 260));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("CREAR CUENTA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        if (this.jButtonMod.getText().equals("Guardar")) {
            this.jButtonMod.setText("Modificar");
            this.txtIidentification.setEnabled(false);
            this.txtPassword.setEnabled(false);
            this.txtName.setEnabled(false);
            this.txtLastName.setEnabled(false);
            this.txtEmail1.setEnabled(false);
            this.txtNumber.setEnabled(false);
            this.txtPassword.setEnabled(false);
            this.txtPasswordConf.setEnabled(false);

            try {

                Client objClientTemp = ObjBLCli.createClient(this.txtIidentification.getText(), String.valueOf(this.txtPasswordConf.getPassword()),
                        this.txtName.getText(), this.txtLastName.getText(), this.txtEmail1.getText(), this.txtNumber.getText());
                objClient = ObjBLCli.updateClientDB(objClient, objClientTemp);
                JOptionPane.showMessageDialog(null, "ACTUALIZADO CON EXITO");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            this.jButtonMod.setText("Guardar");
            this.txtIidentification.setEnabled(true);
            this.txtPassword.setEnabled(true);
            this.txtName.setEnabled(true);
            this.txtLastName.setEnabled(true);
            this.txtEmail1.setEnabled(true);
            this.txtNumber.setEnabled(true);
            this.txtPassword.setEnabled(true);
            this.txtPasswordConf.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonModActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        OptionClient objOptionClient = new OptionClient();
        objOptionClient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        try {
            // TODO add your handling code here:
            Login objLogin = new Login();
            objLogin.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        if (ObjBLCli.validadorDeCedula(this.txtIidentification.getText()) || verifyPasswords()) {
            Client auxObjClient = ObjBLCli.createClient(this.txtIidentification.getText(), String.valueOf(this.txtPasswordConf.getPassword()),
                    this.txtName.getText(), this.txtLastName.getText(), this.txtEmail1.getText(), this.txtNumber.getText());

            try {
                ObjBLCli.insertClientDB(auxObjClient);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    public void validateLogin() {
        Client objAuxClient = new Client();
        objAuxClient = GlobalVariables.loggedClient;
        if (objAuxClient != null) {
            objClient = objAuxClient;
            this.jButtonMod.setVisible(true);
            this.jButtonMod.setEnabled(true);
            this.btnCancelar.setVisible(true);
            this.btnCancelar.setEnabled(true);
            this.btnCrearCuenta.setVisible(false);
            this.btnCrearCuenta.setEnabled(false);
            this.jButtonSalir.setVisible(false);
            this.jButtonSalir.setEnabled(false);
            this.txtIidentification.setText(objAuxClient.getIdentification());
            this.txtName.setText(objAuxClient.getNames());
            this.txtLastName.setText(objAuxClient.getLastnames());
            this.txtEmail1.setText(objAuxClient.getMail());
            this.txtNumber.setText(objAuxClient.getNumberPhone());
            this.txtPassword.setText(objAuxClient.getPassword());
            this.txtIidentification.setEnabled(false);
            this.txtName.setEnabled(false);
            this.txtLastName.setEnabled(false);
            this.txtEmail1.setEnabled(false);
            this.txtNumber.setEnabled(false);
            this.txtPassword.setEnabled(false);
            this.txtPasswordConf.setEnabled(false);
        } else {
            this.btnCrearCuenta.setVisible(true);
            this.btnCrearCuenta.setEnabled(true);
            this.jButtonSalir.setVisible(true);
            this.jButtonSalir.setEnabled(true);
            this.jButtonMod.setVisible(false);
            this.jButtonMod.setEnabled(false);
            this.btnCancelar.setVisible(false);
            this.btnCancelar.setEnabled(false);
        }
    }
    
    private boolean verifyPasswords(){
        String password = this.txtPassword.getText();
        String confirmPassword = this.txtPasswordConf.getText();
        if(password.equals(confirmPassword)){
            return true;
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            return false;
            
        }
    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotons;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtIidentification;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConf;
    // End of variables declaration//GEN-END:variables
}
