/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BL.BLCategory;
import BL.BLEvent;
import CLASES.Category;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import CLASES.Events;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author JIMMY
 */
public class viewAllEvents extends javax.swing.JFrame {
        

    ArrayList<Events> arrayEvents = new ArrayList();
    BLEvent objBLEvents = new BLEvent();
    
    int rowSel = -1;
    /**
     * Creates new form crearEvento
     */
    public viewAllEvents() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jButtonListar.setVisible(false);
        this.getCategories();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SpnCosto = new javax.swing.JSpinner();
        cbmCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrinStr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSecStr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtReferency = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtnNeighborhod = new javax.swing.JTextField();
        jComboBoxHour = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxMinute = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButtonListar = new javax.swing.JButton();
        jcbmCategory = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("VISUALIZAR EVENTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title7", "Title 8"
            }
        ));
        tblEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEventos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 710, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Nombre del evento:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtNombre.setEnabled(false);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Categoria");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Hora de inicio");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        SpnCosto.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        SpnCosto.setEnabled(false);
        jPanel2.add(SpnCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, -1));

        cbmCategory.setEnabled(false);
        jPanel2.add(cbmCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 160, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Fecha");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Descripcion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtDescription.setEnabled(false);
        jPanel2.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 320, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Calle Principal");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtPrinStr.setEnabled(false);
        jPanel2.add(txtPrinStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 320, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Calle Secundaria");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtSecStr.setEnabled(false);
        jPanel2.add(txtSecStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 320, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Referencia");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtReferency.setEnabled(false);
        jPanel2.add(txtReferency, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 320, -1));

        jDateChooser.setEnabled(false);
        jPanel2.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 90, 150, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Barrio");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        txtnNeighborhod.setEnabled(false);
        jPanel2.add(txtnNeighborhod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 320, -1));

        jComboBoxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBoxHour.setEnabled(false);
        jPanel2.add(jComboBoxHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Costo de entrada");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Hora");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 40, -1));

        jLabel13.setText("Minutos");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, -1));

        jComboBoxMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jComboBoxMinute.setEnabled(false);
        jPanel2.add(jComboBoxMinute, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 70, -1));

        jLabel14.setText(":");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 10, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 720, 460));

        jButtonListar.setText("Listar");
        jButtonListar.setEnabled(false);
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 160, -1));

        jcbmCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(jcbmCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 160, -1));

        jLabel15.setText("Escoja una categoria");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 50, 140, -1));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventosMouseClicked
        // TODO add your handling code here:
        this.cbmCategory.removeAllItems();
        rowSel = tblEventos.getSelectedRow();
        this.txtNombre.setText(tblEventos.getValueAt(rowSel, 0).toString());
        this.SpnCosto.setValue(Double.parseDouble(tblEventos.getValueAt(rowSel, 1).toString()));
        this.jDateChooser.setDate(Date.valueOf(tblEventos.getValueAt(rowSel, 2).toString()));
        this.jComboBoxHour.setSelectedItem(arrayEvents.get(rowSel).getHour());
        this.jComboBoxMinute.setSelectedItem(arrayEvents.get(rowSel).getMinutes());
        this.txtDescription.setText(tblEventos.getValueAt(rowSel, 3).toString());
        this.cbmCategory.addItem(tblEventos.getValueAt(rowSel, 4).toString());
        this.txtPrinStr.setText(tblEventos.getValueAt(rowSel, 5).toString());
        this.txtSecStr.setText(tblEventos.getValueAt(rowSel, 6).toString());
        this.txtReferency.setText(tblEventos.getValueAt(rowSel, 7).toString());
        this.txtnNeighborhod.setText(tblEventos.getValueAt(rowSel, 8).toString());
        
    }//GEN-LAST:event_tblEventosMouseClicked

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        
        this.uploadTable();
        
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jcbmCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmCategoryActionPerformed
        this.jButtonListarActionPerformed(evt);
    }//GEN-LAST:event_jcbmCategoryActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        Main objMain = new Main();
        objMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    public void uploadTable(){
            // Listar todos los datos
        this.uploadArrayEvents();
        tblEventos.removeAll();
        Object columnas[] = {"Nombre", "Costo", "Fecha", "Descripcion", "Categoria", "Calle Principal", "Calle Secundaria", "Referencia","Barrio"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        tblEventos.setModel(modelo);
        for(Events event: arrayEvents){
            String newValor[] = {event.getName(), event.getCost()+"", event.getDate()+"", event.getDescription(), event.getCategory().getCategoryName(),
                event.getPlace().getPrincipalStreet(), event.getPlace().getSecondaryStreet(), event.getPlace().getReference(),event.getPlace().getNeighborhood()};

            modelo.addRow(newValor);

        }
    }
    
    // Metodo para actualizar la varible local de arrayEvents
    public void uploadArrayEvents(){
        this.arrayEvents = objBLEvents.listEventsCategory(2,(Category)this.jcbmCategory.getSelectedItem());
        
        
    }
    
    public void getCategories() {
        
        BLCategory objBLCategory = new BLCategory();
        ArrayList<Category> listCategories = new ArrayList<Category>();
        try {
            objBLCategory.getCategories(listCategories);
            DefaultComboBoxModel ModCategories = new DefaultComboBoxModel();           
            for (Category p : listCategories) {
                ModCategories.addElement(p);
            }
            this.jcbmCategory.setModel(ModCategories);
            //this.jcbmCategory.addItem("Todos");
            
        } catch (SQLException e) {
            System.err.println("error");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAllEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAllEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAllEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAllEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAllEvents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnCosto;
    private javax.swing.JComboBox<String> cbmCategory;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxHour;
    private javax.swing.JComboBox<String> jComboBoxMinute;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbmCategory;
    private javax.swing.JTable tblEventos;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrinStr;
    private javax.swing.JTextField txtReferency;
    private javax.swing.JTextField txtSecStr;
    private javax.swing.JTextField txtnNeighborhod;
    // End of variables declaration//GEN-END:variables
}
